### ISSUE TITLE
When I try to build with any collections I get "No matching collection item handler"

### ISSUE THREAD

**Issue by tristanbailey** [tristanbailey/jigsaw-blog#1]
On this site, I was getting casestudies and podcasts to build, now for all three, I get this:

It started with just "posts" or "blogs" it did not like, so I guess I have a tag wrong, though this error seems to point to a missing file.

```
./vendor/bin/jigsaw build

 [Exception]                          
  No matching collection item handler  
```

**Comment by tristanbailey** [comment]
Ok, added a var_dump($file) in this vendor method.

private function getHandler($file)

Looks like if you are testing it on a MacOS filesystem the files try to parse .DS_Store files, which it breaks on for md.

```
object(TightenCo\Jigsaw\File\InputFile)#270 (2) {
  ["file":protected]=>
  object(Symfony\Component\Finder\SplFileInfo)#276 (4) {
    ["relativePath":"Symfony\Component\Finder\SplFileInfo":private]=>
    string(0) ""
    ["relativePathname":"Symfony\Component\Finder\SplFileInfo":private]=>
    string(9) ".DS_Store"
    ["pathName":"SplFileInfo":private]=>
    string(57) "/Users/tristanbailey/git/blog-may/source/_blogs/.DS_Store"
    ["fileName":"SplFileInfo":private]=>
    string(9) ".DS_Store"
  }
  ["basePath":protected]=>
  string(40) "/Users/tristanbailey/git/blog-may/source"
}

```

**Comment by tristanbailey** [comment]
Added to process this step before build:

find source/ -name ".DS_Store" -depth -exec rm {} \;
./vendor/bin/jigsaw build

**Comment by tristanbailey** [comment]
Can not see where to put in an exclusion to remove files from the path. It could be that I have dotfiles set to not hidden and the Symfony package needs the have filter added

**Comment by tristanbailey** [comment]
Ok this might work, add true for hide hidden dot files.


```
CollectionDataLoader ...
    private function buildCollection($collection)
    {
        return collect($this->filesystem->allFiles("{$this->source}/_{$collection->name}", true))
...

SiteBuilder ...
    private function buildSite($source, $destination, $siteData)
    {
        $result = collect($this->files->allFiles($source, true))->map(function ($file) use ($source) {
...

```

**Comment by damiani** [comment]
Great solution, I just updated Jigsaw and tagged a new release with this fix. Thanks!

**Comment by tristanbailey** [comment]
@damiani thanks for your work, and getting it updated, I had not had time to make a patch PR before you replied.

**Comment by tristanbailey** [comment]
ready to test in 1.0.2
